data_dir: /usatlas/atlas01/atlasdisk/users/atlas_wifeng/photon-jet/data
model_dir: /usatlas/atlas01/atlasdisk/users/atlas_wifeng/photon-jet/models_efn_v1.0
output_dir: /usatlas/u/atlas_wifeng/photon-jet/output_efn_v1.0
